name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Install compilers
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ clang

    - name: Install Qt6
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-declarative-dev qt6-wayland patchelf

    - name: Debug Qt6 Installation
      run: |
        ls -la /usr/lib/x86_64-linux-gnu/cmake/Qt6
        ls -la /usr/lib/x86_64-linux-gnu/qt6

    - name: Configure CMake
      run: >
        cmake -B /home/runner/work/dpkg-status/dpkg-status/build
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=Release
        -DQt6_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6
        -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6
        -S /home/runner/work/dpkg-status/dpkg-status/qt

    - name: Build
      run: cmake --build /home/runner/work/dpkg-status/dpkg-status/build --config Release

    - name: Test
      working-directory: /home/runner/work/dpkg-status/dpkg-status/build
      run: ctest -C Release
